dist: xenial
language: python
services:
  - docker
sudo: false

env:
  global:
    - REMOTE_URL: https://github.com/NSLS-II/lightsource2-recipes
    - RECIPES_DIR: recipes-tag
    - DOCKER_IMAGE: nsls2/debian-with-miniconda:v0.1.2
    - TEST_DIR: /test

os:
  - linux
python:
  - 3.6
  - 3.7

script:
  - |
    set -e

    # Git status, etc.
    git status
    git remote add upstream ${REMOTE_URL}
    git remote -v
    git fetch upstream master
    git branch -avv
    git log -n 3

  - env | sort -u

  - |
    set -e

    if [ "${TRAVIS_EVENT_TYPE}" == "pull_request" ]; then
        commit_range="${TRAVIS_COMMIT_RANGE}"
    else
        commit_range="upstream/master...HEAD"
    fi

    # See https://stackoverflow.com/a/7256391/4143531 for details:
    all_changed_files=$(git diff --name-only ${commit_range})
    echo -e "All changed files:\n${all_changed_files}"

    changed_meta_yaml=$(echo "${all_changed_files}" | grep "${RECIPES_DIR}" | grep "meta.yaml" || true)
    echo -e "Changed meta.yaml files:\n${changed_meta_yaml}"

  - |
    set -e

    docker pull ${DOCKER_IMAGE}
    docker images

    if [ ! -z "${changed_meta_yaml}" ]; then
        recipe_dirs=$(echo "${changed_meta_yaml}" | cut -d/ -f 1-2 | sort -u)
        echo -e "Recipe dirs:\n${recipe_dirs}"

        for recipe_dir in ${recipe_dirs}; do
            echo "Building ${recipe_dir}..."
            docker run --rm -it -v $PWD/${recipe_dir}:${TEST_DIR} ${DOCKER_IMAGE} bash -c "conda build ${TEST_DIR} --python=${TRAVIS_PYTHON_VERSION}"
        done
    else
        echo "Nothing to do"
    fi
